### ISSUE TITLE
duplicate shield labels for cities and peaks

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#49]
It seems to be happening at tile boundaries:

![screen shot 2015-11-04 at 5 23 13 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10957391%2Fc8133eea-8318-11e5-9667-18f949cb3056.png)

![](https://cloud.githubusercontent.com/assets/1212178/10949920/3b3fd772-82ea-11e5-8535-e744538dc44d.png)

Oh, but in #35 we found some that were not on tile boundaries, although those seem to be fixed. But that's something to keep an eye on... I _think_ they're only happening on tile boundaries, but I could be wrong.

**Comment by almccon** [comment]
Some of these I'm having trouble duplicating in Tilemill vs Tessera.

For example at zoom 8 in tessera I see this: 
![screen shot 2015-11-04 at 6 18 22 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10958172%2F7d424d54-8320-11e5-9723-560f30994d55.png)

But viewing in Tilemill, Mt. Whitney doesn't even show up, even though other peaks do at the same zoom.
![screen shot 2015-11-04 at 6 18 29 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10958178%2F8f89b966-8320-11e5-85a1-f56576988897.png)

**Comment by clhenrick** [comment]
@almccon here's what I'm seeing in TileMill at z9:
![screen shot 2015-11-05 at 9 04 03 am](https://cloud.githubusercontent.com/assets/161748/10970377/42815cc4-839c-11e5-937e-f58ceff3a007.png)

I was chatting with @mojodna and it seems like part of the problem may be differing versions of Mapnik installed for Tessera and TileMill. After doing `npm ls mapnik` in both the TileMill directory and Terrain-Classic repo I saw that Mapnik was at different versions in each. Seth recommends having both versions of Mapnik at 3.x.

However after bumping up Tessera's Mapnik to ^3.4.9 I was running into an issue where Tessera was crashing. Still attempting to debug...

**Comment by clhenrick** [comment]
On further inspection after bumping mapnik to 3.4.9 and running `tessera -S 50 -c tessera.json` I get the following error:

```
GET /index.json 500 7.751 ms - 1445
Error: Invalid tilesource protocol: blend:
    at Object.tilelive.load (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/tilelive/lib/tilelive.js:92:25)
    at /Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:128:23
    at lock (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:57:16)
    at Object.<anonymous> (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:127:12)
    at Object.load (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:85:17)
    at /Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/lib/app.js:213:21
    at Layer.handle [as handle_request] (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/clhenrick/.nvm/v0.10.40/lib/node_modules/tessera/node_modules/express/lib/router/layer.js:95:5)
```

However when I do `tessera -S 50 mapnik://./terrain-classic.xml` (or `terrain-classic-<variant>`) it works totally fine, minus these errors which I think have to do with Mapnik complaining about CartoCSS?

- `'maxzoom' is deprecated and will be removed in Mapnik 4.x, use 'maximum-scale-denominator' instead`
- `minzoom' is deprecated and will be removed in Mapnik 4.x, use 'minimum-scale-denominator`

Thoughts @mojodna?

**Comment by mojodna** [comment]
Was this from before or after we were debugging this in Slack?

The deprecation warnings are harmless (though it would be nice to see them fixed in CartoCSS), the `Invalid tilesource protocol` error means that `tilelive-blend` needs to be installed.

**Comment by clhenrick** [comment]
@mojodna afterward. 

I did `npm install -g tilelive-blend` while on node v0.10. Ran tessera again and got the following error:

```
/Users/chrislhenrick/development/terrain-classic/node_modules/tilelive-blend/index.js:110
return im1.composite(im2, {
           ^
TypeError: destination image must be premultiplied
```

**Comment by mojodna** [comment]
FWIW, I think the `invalid tilesource protocol` errors are fixed in `tilelive-blend` now.

**Comment by clhenrick** [comment]
Seems like this issue is resolved? cc @almccon @mojodna
